# Generated by Django 3.2.5 on 2021-07-28 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('published', models.DateField(default=None)),
                ('isbn_number', models.CharField(max_length=13, verbose_name='ISBN')),
                ('pages', models.IntegerField(default=0)),
                ('cover', models.CharField(max_length=200)),
                ('language', models.CharField(max_length=200)),
            ],
        ),
    ]
