# Generated by Django 3.2.5 on 2021-08-01 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0012_auto_20210731_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn_number',
            field=models.CharField(max_length=40, verbose_name='ISBN'),
        ),
    ]
